### ISSUE TITLE
CMake Build error

### ISSUE THREAD

**Issue by rolfvdhulst** [CG-SHOP/pyutils23#13] opened 2022-11-07 16:41 UTC
I tried to update the version in order to see which instances the CGSHOP server is rejecting my solutions.
My teammember also has exactly this problem on Windows when using WSL. It seems somewhere in the cmake structure a 'tests' subdirectory is not being found, however the tests directory seems to have a CMakeLists.txt. Commenting this out in CMakeLists.txt also did not help.

Here are the most relevant parts of the error; ( I can provide more if needed, it's fairly long...).

```
 pip install --upgrade cgshop2023-pyutils
Defaulting to user installation because normal site-packages is not writeable
Collecting cgshop2023-pyutils
  Using cached cgshop2023_pyutils-0.2.2.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests>=2.25.1 in /usr/lib/python3/dist-packages (from cgshop2023-pyutils) (2.25.1)
Requirement already satisfied: networkx>=2.5.1 in /home/rolf/.local/lib/python3.10/site-packages (from cgshop2023-pyutils) (2.8.7)
Requirement already satisfied: chardet>=4.0.0 in /usr/lib/python3/dist-packages (from cgshop2023-pyutils) (4.0.0)
Building wheels for collected packages: cgshop2023-pyutils
  Building wheel for cgshop2023-pyutils (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cgshop2023-pyutils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [351 lines of output]
      Configuration:
      [settings]
      arch=x86_64
      arch_build=x86_64
      build_type=Release
      compiler=gcc
      compiler.libcxx=libstdc++
      compiler.version=11
      os=Linux
      os_build=Linux
      [options]
      [build_requires]
      [env]
      
     ....


      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 11.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - success
      --------------------------------------------------------------------------------
      
      Configuring Project
        Working directory:
          /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_skbuild/linux-x86_64-3.10/cmake-build
        Command:
          cmake /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
      
      -- The CXX compiler identification is GNU 11.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Using CCache
      CMake Warning at cmake/CPM.cmake:62 (message):
        Your project is using an unstable development version of CPM.cmake.  Please
        update to a recent release if possible.  See
        https://github.com/cpm-cmake/CPM.cmake for details.
      Call Stack (most recent call first):
        CMakeLists.txt:19 (include)
      
      
      -- CPM: adding package fmt@9.1.0 (9.1.0)
      -- Module support is disabled.
      -- Version: 9.1.0
      -- Build type: Release
      -- CXX_STANDARD: 17
      -- Performing Test has_std_17_flag
      -- Performing Test has_std_17_flag - Success
      -- Performing Test has_std_1z_flag
      -- Performing Test has_std_1z_flag - Success
      -- Required features: cxx_variadic_templates
      -- Conan: Using autogenerated FindCGAL.cmake
      -- Found CGAL: 5.3.2 (found version "5.3.2")
      -- Conan: Using autogenerated FindBoost.cmake
      -- Found Boost: 1.75.0 (found version "1.75.0")


.... (Finding more libraries)


      -- Conan: Using autogenerated Findnlohmann_json.cmake
      -- Found nlohmann_json: 3.11.2 (found version "3.11.2")
      CMake Error at CMakeLists.txt:67 (add_subdirectory):
        add_subdirectory given source "tests" which is not an existing directory.
      
      
      -- CPM: adding package pybind11@2.10.0 (v2.10.0)
      -- pybind11 v2.10.0
      -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.6", minimum required is "3.6")
      -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Configuring incomplete, errors occurred!
      See also "/tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_skbuild/linux-x86_64-3.10/cmake-build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 632, in setup
          env = cmkr.configure(
        File "/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 334, in configure
          raise SKBuildError(
      
      An error occurred while configuring with CMake.
        Command:
          cmake /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.6 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/usr/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so -DPython_EXECUTABLE:PATH=/usr/bin/python3 -DPython_ROOT_DIR:PATH=/usr -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/usr/bin/python3 -DPython3_ROOT_DIR:PATH=/usr -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/usr/lib/python3/dist-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/user/1000/pip-build-env-ohl26poh/overlay/local/lib/python3.10/dist-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe
        Working directory:
          /tmp/user/1000/pip-install-nm4h1zxp/cgshop2023-pyutils_66df537ae9484c648ca2a6b67d28d2fe/_skbuild/linux-x86_64-3.10/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cgshop2023-pyutils
Failed to build cgshop2023-pyutils
ERROR: Could not build wheels for cgshop2023-pyutils, which is required to install pyproject.toml-based projects
```

**Comment by d-krupke** [comment] 2022-11-07 16:48
Interesting. The problem is with
```
      CMake Error at CMakeLists.txt:67 (add_subdirectory):
        add_subdirectory given source "tests" which is not an existing directory.
```
which happens because the tests have not been packed but are in the CMakeLists.txt.
Can you install the package by cloning the repo and simply running `pip install .` in it?

If this is the problem, it is trivial to fix for us.

**Comment by d-krupke** [comment] 2022-11-07 17:27
Should also be fixed in the new release v0.2.4

**Comment by rolfvdhulst** [comment] 2022-11-07 21:34
```pip install .``` indeed works; If I was more experienced with pip/python I would probably have tried that too.
Thanks for your help.

**Comment by d-krupke** [comment] 2022-11-07 21:40
Great! Thanks for reporting this bug, as it seems not to happen on all platforms. We made the CMake more robust. It should now also work simply using the original command without cloning the repository.

**Closed** 2022-11-07 21:41 UTC
